[0m14:23:04.451250 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b45d390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b46d7d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b46ded0>]}


============================== 14:23:04.455612 | ada75451-e3b0-4775-8be1-e8ba4eb954a4 ==============================
[0m14:23:04.455612 [info ] [MainThread]: Running with dbt=1.5.6
[0m14:23:04.455932 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/abhimanyuwadhwa/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:23:04.456417 [debug] [MainThread]: Starter project path: /Users/abhimanyuwadhwa/UdemyCourse/venv/lib/python3.11/site-packages/dbt/include/starter_project
[0m14:27:04.962487 [info ] [MainThread]: Profile dbtlearn written to /Users/abhimanyuwadhwa/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:27:04.967036 [info ] [MainThread]: 
Your new dbt project "dbtlearn" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:27:04.969210 [debug] [MainThread]: Command `dbt init` succeeded at 14:27:04.968784 after 240.53 seconds
[0m14:27:04.970377 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e061d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e1f1d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054ef210>]}
[0m14:27:04.971414 [debug] [MainThread]: Flushing usage events
[0m18:41:09.910957 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118063950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11805e5d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11806bfd0>]}


============================== 18:41:09.914344 | f7243233-b0e2-4560-a666-25163c540032 ==============================
[0m18:41:09.914344 [info ] [MainThread]: Running with dbt=1.5.6
[0m18:41:09.914838 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/abhimanyuwadhwa/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m18:41:09.915237 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/abhimanyuwadhwa/UdemyCourse/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:41:09.915752 [debug] [MainThread]: Command `dbt run` failed at 18:41:09.915665 after 0.03 seconds
[0m18:41:09.916024 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118080890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1031c3050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11805ce50>]}
[0m18:41:09.916287 [debug] [MainThread]: Flushing usage events
[0m23:37:30.307286 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b73b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b725d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b7bf50>]}


============================== 23:37:30.310193 | 7a693506-1b68-42c6-bf30-9147f9ca0416 ==============================
[0m23:37:30.310193 [info ] [MainThread]: Running with dbt=1.5.6
[0m23:37:30.310483 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/abhimanyuwadhwa/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m23:37:30.310738 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/abhimanyuwadhwa/UdemyCourse/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:37:30.311055 [debug] [MainThread]: Command `dbt test` failed at 23:37:30.310999 after 0.02 seconds
[0m23:37:30.311204 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x101416b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1012c30d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b6cbd0>]}
[0m23:37:30.311352 [debug] [MainThread]: Flushing usage events
